version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run:
          name: run build
          command: |
            dep ensure
            go build -v
      - run: go test -v ./...
  test:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go test -v ./...
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test